version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@octokit/types"
    versions:
    - 6.10.0
    - 6.10.1
    - 6.11.0
    - 6.11.1
    - 6.11.2
    - 6.12.0
    - 6.12.1
    - 6.12.2
    - 6.13.0
    - 6.13.1
    - 6.13.2
    - 6.14.0
    - 6.6.0
    - 6.7.0
    - 6.7.1
    - 6.8.2
    - 6.8.3
    - 6.8.4
    - 6.8.5
    - 6.9.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.0
    - 0.38.1
    - 0.38.2
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
