name: lint_pr

on: pull_request

jobs:
  xo:
    name: xo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
      - name: xo
        run: npm run lint
